import sys
import codecs
import os 
import csv
from pathlib import Path
import datetime
import collections

'''
visualizationPreProcessing
Author: Danielle Gonzalez dng2551@rit.edu

This program processes the CSV files generated by getRepoData to organize the data in a way that is easier to visualize.
The goal of RepoVis is to make project chatacteristics across releases (or tags if there are no releases)
Therefore, the data collected needs to be organized into release-based collections of data

Note: the code currently looks to see if there are releases. If there are, then data is organized by release
If there are no releases, this operation cannot be performed

Current Metadata Organized :
1. Issues
2. Pull Requests
Contributor's can't be organized by release (but we can count how many PRS or issues they open in a release!)

PROGRAM INPUT:
	1. the name of the repository (CSV files from previous step are labeled REPONAME-METADATA.csv, for example 'atom-contributors.csv')
	2. the root directory (relative to the location of this script) Example: ../data
		Note: default location to place files in previous step is in the /data folder, but I am requesting a path in case they were moved
		or placed in a subfolder. 

PROGRAM OUTPUT: 
	1. 2 CSV files containing the issues and pull requests with release data included (Date Opened)
	   A PR or Issue is assigned to the EARLIEST release that happened AFTER it was opened
	   
   	2. 2 CSV files containing the issues and pull requests with release data included (Date Closed)
   	   A PR or Issue is assigned to the EARLIEST release that happened AFTER it was opened
   
    3. 1 CSV file containing the contributors who opened pull requests and issues sorted by release 

'''

def writeDataToFile(data, outputPath, dataType):
	outFile = open(outputPath, "a", encoding="utf-8")
	firstItem = next(iter(data.values())) #get any dict value
	try:
		# Create the header with the attribute names
		for attrib in firstItem:
			outFile.write(str(attrib) + ",")
		outFile.write('\n')
		# Add data to the CSV
		for record in data:
			row = data[record]
			for attribute in row:
				#print(row[attribute])
				outFile.write(str(row[attribute]) + ",")
			outFile.write("\n")
	except Exception as exc:
		print("Generated an exception during " + str(dataType) + " output: " + str(exc))
	else:
		print(str(dataType) + " data has been output to " + str(outputPath))
		outFile.close()


'''
organizeByDate

groups PRs and Issues into releases

NOTE: This currently ignores data created or closed AFTER the last release date

INPUT:
	1. sortBy: a STRING, either 'created_at' or closed_at'. 
	2. releases: a DICTIONARY with key as release name and value is a python date object
	5. pullRequests: a DICTIONARY with key as pr number and value as other pr data
	6. issues: a DICTIONARY with key as issue number and value as other issue data
	7. repoName: a STRING of the repo name, for output purposes

OUTPUT: 
	None, but outputs combined data into csv with release name and date added as new columns

'''
def organizeByDate(sortBy,releases,pullRequests,issues,repoName):

	print("Organizing " + str(len(pullRequests)) + " Pull Requests by Release Date...")
	for pr in pullRequests:
		#get all releases that happened after the pr was opened, then sort this list by date
		if pullRequests[pr][sortBy] != 'None':
			prDate = datetime.datetime.strptime(pullRequests[pr][sortBy], "%Y-%m-%dT%H:%M:%SZ")
			possiblePRReleases = dict((k, v) for k, v in releases.items() if v >= prDate)
			
			if len(possiblePRReleases) > 0:
				# the earliest release that happened AFTER the PR was opened or closed is selected as the release
				# for example, all PRs opened before the first release 'belong' to that release
				prRelease = sorted(possiblePRReleases, key=possiblePRReleases.get)[0]
				pullRequests[pr]['release_Date'] = releases[prRelease].strftime("%Y-%m-%dT%H:%M:%SZ")
				pullRequests[pr]['release_Name'] = prRelease

	print("Organizing " + str(len(issues)) + " Issues by Release Date...")
	for issue in issues:
		#get all releases that happened after the pr was opened, then sort this list by date
		if issues[issue][sortBy] != 'None':
			issueDate = datetime.datetime.strptime(issues[issue][sortBy], "%Y-%m-%dT%H:%M:%SZ")
			possibleIssueReleases = dict((k, v) for k, v in releases.items() if v >= issueDate)
			
			if len(possibleIssueReleases) > 0:
				# the earliest release that happened AFTER the PR was opened or closed is selected as the release
				# for example, all PRs opened before the first release 'belong' to that release
				issueRelease = sorted(possibleIssueReleases, key=possibleIssueReleases.get)[0]
				issues[issue]['release_Date'] = releases[issueRelease].strftime("%Y-%m-%dT%H:%M:%SZ")
				issues[issue]['release_Name'] = issueRelease
			
	pullRequestOutput = "../data/" + str(repoName) + "-pullrequests-Releases-" + str(sortBy) + ".csv"
	issueOutput = "../data/" + str(repoName) + "-issues-Releases-" + str(sortBy) + ".csv"
	
	writeDataToFile(pullRequests,pullRequestOutput, "Pull Requests (" + str(sortBy) + ")")
	writeDataToFile(issues, issueOutput, "Issue (" + str(sortBy) + ")")



		


'''
main method

Checks that necessary CSV files exist, and gets release data
Calls sortDataByRelease 
'''
def main():

	if(len(sys.argv) < 3):
		print("Please include the following arguments, in this order: ")
		print("Repository Name, Root Folder for CSV Files")
	else:
		# get input arguments
		repoName = sys.argv[1]
		dataPath = sys.argv[2]

		# get the CSV files and make sure they exists
		try:
			releasesCSV = Path(str(dataPath) + "/" + str(repoName) + "-releases.csv").resolve()
			pullRequestCSV = Path(str(dataPath) + "/" + str(repoName) + "-pullrequests.csv").resolve()
			issuesCSV = Path(str(dataPath) + "/" + str(repoName) + "-issues.csv").resolve()
		except FileNotFoundError as f:
			print(f)

		# first step is to make an object for the release data 
		with releasesCSV.open() as releaseFile:
			releaseReader = csv.DictReader(releaseFile)
			
			#put the releases into a dictionary containing the release name and date
			releases = {} 
			for row in releaseReader:
				#transform the string date (ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ) into Python date object
				releases[row['name']] = datetime.datetime.strptime(row['created_at'], "%Y-%m-%dT%H:%M:%SZ")
			
			#If there aren't any releases, you need to select a different project!
			if len(releases) == 0:
				print("No Releases! Sorry, please choose another project.")
			else:
				print(str(len(releases)) + " Releases found!")

				# put pull request data in a dict
				with pullRequestCSV.open() as prFile:
					prReader = csv.DictReader(prFile)
					pullRequests = {}
					for row in prReader:
						pullRequests[row['number']] = row
				prFile.close()

				# put issue data in a dict
				with issuesCSV.open() as issueFile:
					issueReader = csv.DictReader(issueFile)
					issues = {}
					for row in issueReader:
						issues[row['number']] = row
				issueFile.close()	
		releaseFile.close()
		# organize the PR and issue data by date opened and closed
		organizeByDate('created_at', releases, pullRequests, issues, repoName)
		organizeByDate('closed_at', releases, pullRequests, issues,repoName)
main() 